### ISSUE TITLE
Сокращенное название месяца

### ISSUE THREAD

**Issue by Typodin** [SergeyMiracle/aDate#2]
В языковом файле для коротких названий месяцев Июль записан полностью, сбивает с толку.

**Comment by SergeyMiracle** [comment]
Предложение?

**Comment by Typodin** [comment]
Убрать мягкий знак в языковом файле)

**Comment by Typodin** [comment]
Если всем по три буквы, то и этому три буквы.

**Comment by SergeyMiracle** [comment]
Изменен (версия 1.0.1)
